### ISSUE TITLE
FR: confusion entre fichiers de agneau et ceux de parking

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/kinephone#11]
FR: confusion entre fichiers de agneau et ceux de parking
au lieu de

![agneau_parking_pb1a](https://cloud.githubusercontent.com/assets/6398284/6285086/051190f8-b8f8-11e4-994d-fa5cbd4d58cd.jpg)

c'est

![agneau_parking_pb1b](https://cloud.githubusercontent.com/assets/6398284/6285093/0fa5fe64-b8f8-11e4-9da7-51720658ac10.jpg)

**Comment by eldoniel** [comment]
Corrigé, les fichiers de "agneau" sont à la bonne place (ceux de "parking" ne sont pas disponibles)
