### ISSUE TITLE
url params

### ISSUE THREAD

**Issue by pitrackster** [InnovaLangues/kinephone#3]
Actuellement l'url d'entrée dans l'application est la suivante : 

- /kinephone/#/1/1/table
 Les deux chiffres de l'url correspondent dans l'ordre à language_id puis table_id et enfin table désigne la vue "tableau" (cf kinephoneApi)

1 - il n'y a pas de point d'entrée par défaut si on a une mauvaise url (redirection sur page d'erreur ou valeurs par défaut)
2 - Il serait plus judicieux d'utiliser les codes des langues (en_en, fr_fr, en_us...) ainsi que les types/noms des tableaux (couleur, phonem, dessins) avec chaque fois une vérification et une valeur par défaut ou redirection si les paramètres ne sont pas valides

**Comment by eldoniel** [comment]
Un point d'entrée par défaut a été ajouté. Les codes des langues ont été intégrés à l'url, en revanche ce n'est pas le cas pour le type des tableaux.
